// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace MLPredictHousingML.Model
{
    public class ModelInput
    {
        [ColumnName("CRIM"), LoadColumn(0)]
        public float CRIM { get; set; }


        [ColumnName("ZN"), LoadColumn(1)]
        public float ZN { get; set; }


        [ColumnName("INDUS"), LoadColumn(2)]
        public float INDUS { get; set; }


        [ColumnName("CHAS"), LoadColumn(3)]
        public float CHAS { get; set; }


        [ColumnName("NOX"), LoadColumn(4)]
        public float NOX { get; set; }


        [ColumnName("RM"), LoadColumn(5)]
        public float RM { get; set; }


        [ColumnName("AGE"), LoadColumn(6)]
        public float AGE { get; set; }


        [ColumnName("DIS"), LoadColumn(7)]
        public float DIS { get; set; }


        [ColumnName("RAD"), LoadColumn(8)]
        public float RAD { get; set; }


        [ColumnName("TAX"), LoadColumn(9)]
        public float TAX { get; set; }


        [ColumnName("PTRATIO"), LoadColumn(10)]
        public float PTRATIO { get; set; }


        [ColumnName("B"), LoadColumn(11)]
        public float B { get; set; }


        [ColumnName("LSTAT"), LoadColumn(12)]
        public float LSTAT { get; set; }


        [ColumnName("MEDV"), LoadColumn(13)]
        public float MEDV { get; set; }

        public override string ToString()
        {
            string rv = $"CRIM:{this.CRIM, -7}"
                        + $" ZN:{this.ZN, -4}"
                        + $" INDUS:{this.INDUS, -5}"
                        + $" CHAS:{this.CHAS}"
                        + $" NOX:{this.NOX, -6}"
                        + $" RM:{this.RM, -5}"
                        + $" AGE:{this.AGE, -4}"
                        + $" DIS:{this.DIS, -7}"
                        + $" RAD:{this.RAD, -2}"
                        + $" TAX:{this.TAX, -3}"
                        + $" PTRATIO:{this.PTRATIO, -4}"
                        + $" B:{this.B, -6}"
                        + $" LSTAT:{this.LSTAT, -5}"
                        + $"  ==>  MEDV:{this.MEDV, -4}";
            return rv;
        }
    }

} // end of namespace
